services:
  mongodb:
    image: mongo:8.0.0
    volumes:
      - dbdata:/data/db
    restart: unless-stopped
    pids_limit: 512
    mem_limit: 512m
    cpus: 1

  search:
    build: search
    volumes:
      - searchdata:/data
    environment:
      - "INDEX_FILE=/data/bleve.index"
    restart: unless-stopped
    pids_limit: 512
    mem_limit: 512m
    cpus: 1

  api:
    build: api
    restart: unless-stopped
    depends_on:
      - mongodb
      - search
    pids_limit: 512
    mem_limit: 1g
    cpus: 2

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./conf/app.conf:/etc/nginx/conf.d/default.conf
      - ./front/build:/front/build
    depends_on:
      - api
    pids_limit: 512
    mem_limit: 256m
    cpus: 1

volumes:
  dbdata:
  searchdata: