version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ctr1panel_postgres
    restart: always
    environment:
      POSTGRES_DB: ctr1panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes: 
      - ctr1panel_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ctr1panel"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ctr1panel_net
    
  server:
    container_name: ctr1panel_server
    restart: always
    build:
      context: .
    ports:
      - "11000:11000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - ctr1panel_net

volumes:
  ctr1panel_postgres_data:

networks:
  ctr1panel_net:
    driver: bridge
